export const langObj = {
    javascript: "JavaScript",
    python: "Python",
    java: "Java",
    csharp: "C#",
    swift: "Swift",
    sql: "SQL",
    prolog: "Prolog",
    kotlin: "Kotlin",
    c: "C",
    scala: "Scala",
    ruby: "Ruby",
    r: "R",
    haskell: "Haskell",
    elixir: "Elixir",
    dart: "Dart",
    typescript: "TypeScript",
    coffeescript: "CoffeeScript",
    rust: "Rust",
    go: "Golang",
    cpp: "C++",
    fsharp: "F Sharp",
    ocaml: "OCaml",
    crystal: "Crystal",
    clojure: "Clojure",
    nim: "Nim",
    objc: "Objective-C",
    groovy: "Groovy",
    solidity: "Solidity",
    erlang: "Erlang",
    fortran: "Fortran",
    julia: "Julia",
    shell: "Shell",
    powershell: "PowerShell",
    reason: "Reason",
    racket: "Racket",
    vb: "Visual Basic",
    forth: "Forth",
    factor: "Factor",
    cobol: "COBOL ",
    coq: "Coq",
    haxe: "Haxe",
    elm: "Elm ",
    cfml: "CFML",
    purescript: "PureScript ",
    commonlisp: "Common Lisp",
    perl: "Perl",
    raku: "Raku",
    pascal: "Pascal",
    d: "D",
};